# Generated by Django 3.1.3 on 2021-08-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bady',
            new_name='body',
        ),
    ]
